spring.application.name=backend

# Database Configuration (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/myapp
spring.datasource.username=myuser
spring.datasource.password=mypassword
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration (Secret Key? ?? 256bit ????? ??? ??? ? ???? Base64 ???? ? ??)
# ?? ?? ????? ?? ??(Environment Variable)? ???? ???.
jwt.secret=Y29tLnNuc2FpLmJhY2tlbmQuc2VjcmV0LmtleS5mb3Iuand0LnZlcnkuc2VjdXJlLmNvZGU=
jwt.access-token-validity-in-seconds=3600
jwt.refresh-token-validity-in-seconds=604800
